/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uas.app;

import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lApl = new javax.swing.JLabel();
        namaFile = new javax.swing.JTextField();
        bBrowser = new javax.swing.JButton();
        scrollData = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        bEkspor = new javax.swing.JButton();
        bStatistik = new javax.swing.JButton();
        lPersen = new javax.swing.JLabel();
        panelPersen = new javax.swing.JPanel();
        persenTugas = new javax.swing.JSpinner();
        persenUTS = new javax.swing.JSpinner();
        persenUAS = new javax.swing.JSpinner();
        lPersenTugas = new javax.swing.JLabel();
        lPersenUTS = new javax.swing.JLabel();
        lPersenUAS = new javax.swing.JLabel();
        bHitungPersen = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(90, 0), new java.awt.Dimension(90, 0), new java.awt.Dimension(90, 32767));
        menuApl = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        about = new javax.swing.JMenu();
        apl = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pengolah Nilai");
        setMinimumSize(new java.awt.Dimension(630, 540));
        setName("Frame Utama"); // NOI18N
        setPreferredSize(new java.awt.Dimension(630, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(630, 570));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 16, 0, 16, 0, 16, 0};
        layout.rowHeights = new int[] {0, 14, 0, 14, 0, 14, 0, 14, 0};
        getContentPane().setLayout(layout);

        lApl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lApl.setText("Aplikasi Pengolah Nilai");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        getContentPane().add(lApl, gridBagConstraints);

        namaFile.setEditable(false);
        namaFile.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        namaFile.setText("Nama Berkas Nilai...");
        namaFile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        namaFile.setMinimumSize(new java.awt.Dimension(150, 25));
        namaFile.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(namaFile, gridBagConstraints);

        bBrowser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bBrowser.setText("Browse");
        bBrowser.setMaximumSize(new java.awt.Dimension(100, 45));
        bBrowser.setMinimumSize(new java.awt.Dimension(75, 25));
        bBrowser.setPreferredSize(new java.awt.Dimension(70, 25));
        bBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBrowserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        getContentPane().add(bBrowser, gridBagConstraints);

        scrollData.setMinimumSize(new java.awt.Dimension(450, 200));

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "NPM", "Tugas", "UTS", "UAS", "Nilai AKhir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelData.setFillsViewportHeight(true);
        tabelData.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tabelData.setName("TabelData"); // NOI18N
        tabelData.setRowHeight(20);
        tabelData.setRowMargin(2);
        tabelData.setRowSelectionAllowed(false);
        tabelData.getTableHeader().setReorderingAllowed(false);
        scrollData.setViewportView(tabelData);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(scrollData, gridBagConstraints);

        bEkspor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bEkspor.setText("Ekspor");
        bEkspor.setMaximumSize(bBrowser.getMaximumSize());
        bEkspor.setMinimumSize(bBrowser.getMinimumSize());
        bEkspor.setPreferredSize(bBrowser.getPreferredSize());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        getContentPane().add(bEkspor, gridBagConstraints);

        bStatistik.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bStatistik.setText("Statistik");
        bStatistik.setMaximumSize(bBrowser.getMaximumSize());
        bStatistik.setMinimumSize(new java.awt.Dimension(80, 25));
        bStatistik.setPreferredSize(bBrowser.getPreferredSize());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        getContentPane().add(bStatistik, gridBagConstraints);

        lPersen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lPersen.setText("Hitung Nilai Akhir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lPersen, gridBagConstraints);

        panelPersen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelPersen.setMinimumSize(new java.awt.Dimension(300, 160));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 16, 0, 16, 0};
        jPanel1Layout.rowHeights = new int[] {0, 14, 0, 14, 0};
        panelPersen.setLayout(jPanel1Layout);

        persenTugas.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        persenTugas.setMinimumSize(new java.awt.Dimension(60, 30));
        persenTugas.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panelPersen.add(persenTugas, gridBagConstraints);

        persenUTS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        persenUTS.setMinimumSize(new java.awt.Dimension(60, 30));
        persenUTS.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        panelPersen.add(persenUTS, gridBagConstraints);

        persenUAS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        persenUAS.setMinimumSize(new java.awt.Dimension(60, 30));
        persenUAS.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        panelPersen.add(persenUAS, gridBagConstraints);

        lPersenTugas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lPersenTugas.setText("Persentase Tugas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelPersen.add(lPersenTugas, gridBagConstraints);

        lPersenUTS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lPersenUTS.setText("Persentase UTS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelPersen.add(lPersenUTS, gridBagConstraints);

        lPersenUAS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lPersenUAS.setText("Persentase UAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelPersen.add(lPersenUAS, gridBagConstraints);

        bHitungPersen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bHitungPersen.setText("Hitung");
        bHitungPersen.setMaximumSize(new java.awt.Dimension(100, 45));
        bHitungPersen.setMinimumSize(new java.awt.Dimension(70, 25));
        bHitungPersen.setPreferredSize(new java.awt.Dimension(70, 25));
        bHitungPersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungPersenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        panelPersen.add(bHitungPersen, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(panelPersen, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        getContentPane().add(filler1, gridBagConstraints);

        file.setText("Berkas");
        menuApl.add(file);

        about.setText("Tentang");

        apl.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        apl.setText("Tentang Aplikasi");
        apl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplActionPerformed(evt);
            }
        });
        about.add(apl);

        menuApl.add(about);

        setJMenuBar(menuApl);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHitungPersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungPersenActionPerformed
        // TODO add your handling code here:
        int persen = (int) persenTugas.getValue() + (int) persenUTS.getValue() + (int) persenUAS.getValue();
        if (persen == 100) {

        } else {
            JOptionPane.showMessageDialog(null, "Persentase Kurang dari 100%", "Perhatian", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bHitungPersenActionPerformed

    private void aplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Nama:\nIlham Taufik Hidayat - 1842807\nBayu Pamungkas - 1841801", "Dibuat Oleh", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_aplActionPerformed

    private void bBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBrowserActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        if (evt.getSource() == bBrowser) {
            int returnVal = fc.showOpenDialog(MainFrame.this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();

                namaFile.setText(file.getName());

                try {
                    FileReader reader = new FileReader(file);
                    CSVReader csvr = new CSVReaderBuilder(reader).build();
                    List<String[]> allData = csvr.readAll();
                    DefaultTableModel model = (DefaultTableModel) tabelData.getModel();
                    model.setRowCount(allData.size());
                    String[][] raw = new String[allData.size()][tabelData.getColumnCount()];
                    for (String[] column : allData) {
                        int i = allData.indexOf(column);
                        for (int j = 0; j < tabelData.getColumnCount(); j++) {
                            raw[i][j] = column[j];
                            tabelData.setValueAt(raw[i][j], i, j);
                        }
                    } 
                } catch (Exception ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_bBrowserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JMenuItem apl;
    private javax.swing.JButton bBrowser;
    private javax.swing.JButton bEkspor;
    private javax.swing.JButton bHitungPersen;
    private javax.swing.JButton bStatistik;
    private javax.swing.JMenu file;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel lApl;
    private javax.swing.JLabel lPersen;
    private javax.swing.JLabel lPersenTugas;
    private javax.swing.JLabel lPersenUAS;
    private javax.swing.JLabel lPersenUTS;
    private javax.swing.JMenuBar menuApl;
    private javax.swing.JTextField namaFile;
    private javax.swing.JPanel panelPersen;
    private javax.swing.JSpinner persenTugas;
    private javax.swing.JSpinner persenUAS;
    private javax.swing.JSpinner persenUTS;
    private javax.swing.JScrollPane scrollData;
    private javax.swing.JTable tabelData;
    // End of variables declaration//GEN-END:variables
}
