/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uas.app;

import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import com.opencsv.CSVWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.knowm.xchart.XChartPanel;

/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    ChartPengolah cp = new ChartPengolah();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lApl = new javax.swing.JLabel();
        namaFile = new javax.swing.JTextField();
        bBrowser = new javax.swing.JButton();
        scrollData = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        bEkspor = new javax.swing.JButton();
        bStatistik = new javax.swing.JButton();
        lPersen = new javax.swing.JLabel();
        panelPersen = new javax.swing.JPanel();
        lPersenTugas = new javax.swing.JLabel();
        lPersenUTS = new javax.swing.JLabel();
        lPersenUAS = new javax.swing.JLabel();
        bHitungPersen = new javax.swing.JButton();
        persenTugas = new javax.swing.JComboBox();
        persenUTS = new javax.swing.JComboBox();
        persenUAS = new javax.swing.JComboBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(90, 0), new java.awt.Dimension(90, 0), new java.awt.Dimension(90, 32767));
        menuApl = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        mBrowse = new javax.swing.JMenuItem();
        mExport = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mExit = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        apl = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pengolah Nilai");
        setMinimumSize(new java.awt.Dimension(630, 540));
        setName("Frame Utama"); // NOI18N
        setPreferredSize(new java.awt.Dimension(630, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(630, 570));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 16, 0, 16, 0, 16, 0};
        layout.rowHeights = new int[] {0, 14, 0, 14, 0, 14, 0, 14, 0};
        getContentPane().setLayout(layout);

        lApl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lApl.setText("Aplikasi Pengolah Nilai");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        getContentPane().add(lApl, gridBagConstraints);

        namaFile.setEditable(false);
        namaFile.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        namaFile.setText("Nama Berkas Nilai...");
        namaFile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        namaFile.setMinimumSize(new java.awt.Dimension(150, 25));
        namaFile.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(namaFile, gridBagConstraints);

        bBrowser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bBrowser.setText("Browse");
        bBrowser.setMaximumSize(new java.awt.Dimension(100, 45));
        bBrowser.setMinimumSize(new java.awt.Dimension(75, 25));
        bBrowser.setPreferredSize(new java.awt.Dimension(70, 25));
        bBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBrowserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        getContentPane().add(bBrowser, gridBagConstraints);

        scrollData.setMinimumSize(new java.awt.Dimension(450, 200));

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "NPM", "Tugas", "UTS", "UAS", "Nilai AKhir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelData.setFillsViewportHeight(true);
        tabelData.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tabelData.setName("TabelData"); // NOI18N
        tabelData.setRowHeight(20);
        tabelData.setRowMargin(2);
        tabelData.setRowSelectionAllowed(false);
        tabelData.getTableHeader().setReorderingAllowed(false);
        scrollData.setViewportView(tabelData);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(scrollData, gridBagConstraints);

        bEkspor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bEkspor.setText("Ekspor");
        bEkspor.setMaximumSize(bBrowser.getMaximumSize());
        bEkspor.setMinimumSize(bBrowser.getMinimumSize());
        bEkspor.setPreferredSize(bBrowser.getPreferredSize());
        bEkspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEksporActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        getContentPane().add(bEkspor, gridBagConstraints);

        bStatistik.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bStatistik.setText("Statistik");
        bStatistik.setMaximumSize(bBrowser.getMaximumSize());
        bStatistik.setMinimumSize(new java.awt.Dimension(80, 25));
        bStatistik.setPreferredSize(bBrowser.getPreferredSize());
        bStatistik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStatistikActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        getContentPane().add(bStatistik, gridBagConstraints);

        lPersen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lPersen.setText("Hitung Nilai Akhir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lPersen, gridBagConstraints);

        panelPersen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelPersen.setMinimumSize(new java.awt.Dimension(300, 160));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 16, 0, 16, 0};
        jPanel1Layout.rowHeights = new int[] {0, 14, 0, 14, 0};
        panelPersen.setLayout(jPanel1Layout);

        lPersenTugas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lPersenTugas.setText("Persentase Tugas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelPersen.add(lPersenTugas, gridBagConstraints);

        lPersenUTS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lPersenUTS.setText("Persentase UTS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelPersen.add(lPersenUTS, gridBagConstraints);

        lPersenUAS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lPersenUAS.setText("Persentase UAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelPersen.add(lPersenUAS, gridBagConstraints);

        bHitungPersen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bHitungPersen.setText("Hitung");
        bHitungPersen.setMaximumSize(new java.awt.Dimension(100, 45));
        bHitungPersen.setMinimumSize(new java.awt.Dimension(70, 25));
        bHitungPersen.setPreferredSize(new java.awt.Dimension(70, 25));
        bHitungPersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungPersenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        panelPersen.add(bHitungPersen, gridBagConstraints);

        persenTugas.setMaximumRowCount(21);
        persenTugas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100" }));
        persenTugas.setMinimumSize(new java.awt.Dimension(60, 30));
        persenTugas.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panelPersen.add(persenTugas, gridBagConstraints);

        persenUTS.setMaximumRowCount(21);
        persenUTS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100" }));
        persenUTS.setMinimumSize(new java.awt.Dimension(60, 30));
        persenUTS.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        panelPersen.add(persenUTS, gridBagConstraints);

        persenUAS.setMaximumRowCount(21);
        persenUAS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100" }));
        persenUAS.setMinimumSize(new java.awt.Dimension(60, 30));
        persenUAS.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        panelPersen.add(persenUAS, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(panelPersen, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        getContentPane().add(filler1, gridBagConstraints);

        file.setText("Berkas");

        mBrowse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mBrowse.setText("Pilih Berkas....");
        mBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBrowseActionPerformed(evt);
            }
        });
        file.add(mBrowse);

        mExport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mExport.setText("Simpan Sebagai...");
        mExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExportActionPerformed(evt);
            }
        });
        file.add(mExport);
        file.add(jSeparator1);

        mExit.setText("Keluar");
        mExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitActionPerformed(evt);
            }
        });
        file.add(mExit);

        menuApl.add(file);

        about.setText("Tentang");

        apl.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        apl.setText("Tentang Aplikasi");
        apl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplActionPerformed(evt);
            }
        });
        about.add(apl);

        menuApl.add(about);

        setJMenuBar(menuApl);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHitungPersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungPersenActionPerformed
        // TODO add your handling code here:
        int persen = Integer.parseInt(persenTugas.getSelectedItem().toString()) + Integer.parseInt(persenUTS.getSelectedItem().toString()) + Integer.parseInt(persenUAS.getSelectedItem().toString());
        if (persen == 100) {
            for (int i = 0; i < tabelData.getRowCount(); i++) {
                int nilai = nilaiAkhir(i);
                if (nilai == 0) {
                    tabelData.setValueAt("T", i, 5);
                } else if (nilai < 50) {
                    tabelData.setValueAt("E", i, 5);
                } else if (50 <= nilai && nilai < 60) {
                    tabelData.setValueAt("D", i, 5);
                } else if (60 <= nilai && nilai < 70) {
                    tabelData.setValueAt("C", i, 5);
                } else if (70 <= nilai && nilai < 80) {
                    tabelData.setValueAt("B", i, 5);
                } else {
                    tabelData.setValueAt("A", i, 5);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Persentase Tidak Sama dengan 100%", "Perhatian", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bHitungPersenActionPerformed

    private void aplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Nama:\nIlham Taufik Hidayat - 1842807\nBayu Pamungkas - 1841801", "Dibuat Oleh", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_aplActionPerformed

    private void bBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBrowserActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();

        fc.setFileFilter(new FileNameExtensionFilter("CSV File", "csv"));
        int returnVal = fc.showOpenDialog(MainFrame.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File open = fc.getSelectedFile();

            namaFile.setText(open.getName());

            try {
                FileReader reader = new FileReader(open);
                CSVReader csvr = new CSVReaderBuilder(reader).build();
                List<String[]> allData = csvr.readAll();
                DefaultTableModel model = (DefaultTableModel) tabelData.getModel();

                model.setRowCount(allData.size());
                String[][] raw = new String[allData.size()][tabelData.getColumnCount()];

                for (String[] column : allData) {
                    int i = allData.indexOf(column);
                    for (int j = 0; j < tabelData.getColumnCount(); j++) {
                        if (j != (tabelData.getColumnCount() - 1)) {
                            if ("".equals(column[j])) {
                                column[j] = "0";
                                raw[i][j] = column[j];
                                tabelData.setValueAt(raw[i][j], i, j);
                            } else {
                                raw[i][j] = column[j];
                                tabelData.setValueAt(raw[i][j], i, j);
                            }
                        } else {
                            tabelData.setValueAt("", i, j);
                        }
                    }
                }

                JOptionPane.showMessageDialog(null, "Silahkan atur Persentase Nilai "
                        + "untuk Mendapatkan Nilai Akhir", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bBrowserActionPerformed

    private void bEksporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEksporActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();

        fc.setCurrentDirectory(new File("."));
        fc.setFileFilter(new FileNameExtensionFilter("CSV File", "csv"));
        int rSave = fc.showSaveDialog(MainFrame.this);

        if (rSave == JFileChooser.APPROVE_OPTION) {
            File save = fc.getSelectedFile();

            try {
                CSVWriter csvw = new CSVWriter(new FileWriter(save));
                List<String[]> dataSave = new ArrayList<>();

                String[] dataHeader = {tabelData.getColumnName(0), tabelData.getColumnName(1),
                    tabelData.getColumnName(2), tabelData.getColumnName(3),
                    tabelData.getColumnName(4), tabelData.getColumnName(5)};
                dataSave.add(dataHeader);
                for (int i = 0; i < tabelData.getRowCount(); i++) {
                    String[] dataNilai = {tabelData.getValueAt(i, 0).toString(),
                        tabelData.getValueAt(i, 1).toString(),
                        tabelData.getValueAt(i, 2).toString(),
                        tabelData.getValueAt(i, 3).toString(),
                        tabelData.getValueAt(i, 4).toString(),
                        tabelData.getValueAt(i, 5).toString()};
                    dataSave.add(dataNilai);
                }
                csvw.writeAll(dataSave);
                csvw.close();
            } catch (Exception e) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_bEksporActionPerformed

    private void mBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBrowseActionPerformed
        // TODO add your handling code here:
        bBrowserActionPerformed(evt);
    }//GEN-LAST:event_mBrowseActionPerformed

    private void mExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExportActionPerformed
        // TODO add your handling code here:
        bEksporActionPerformed(evt);
    }//GEN-LAST:event_mExportActionPerformed

    private void mExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mExitActionPerformed

    private void bStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStatistikActionPerformed
        // TODO add your handling code here:
        new StatFrame().setVisible(true);
    }//GEN-LAST:event_bStatistikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JMenuItem apl;
    private javax.swing.JButton bBrowser;
    private javax.swing.JButton bEkspor;
    private javax.swing.JButton bHitungPersen;
    private javax.swing.JButton bStatistik;
    private javax.swing.JMenu file;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lApl;
    private javax.swing.JLabel lPersen;
    private javax.swing.JLabel lPersenTugas;
    private javax.swing.JLabel lPersenUAS;
    private javax.swing.JLabel lPersenUTS;
    private javax.swing.JMenuItem mBrowse;
    private javax.swing.JMenuItem mExit;
    private javax.swing.JMenuItem mExport;
    private javax.swing.JMenuBar menuApl;
    private javax.swing.JTextField namaFile;
    private javax.swing.JPanel panelPersen;
    private javax.swing.JComboBox persenTugas;
    private javax.swing.JComboBox persenUAS;
    private javax.swing.JComboBox persenUTS;
    private javax.swing.JScrollPane scrollData;
    private javax.swing.JTable tabelData;
    // End of variables declaration//GEN-END:variables

    public int nilaiAkhir(int i) {
        int nilai = ((Integer.parseInt(tabelData.getValueAt(i, 2).toString()) * Integer.parseInt(persenTugas.getSelectedItem().toString())) / 100)
                + ((Integer.parseInt(tabelData.getValueAt(i, 3).toString()) * Integer.parseInt(persenUTS.getSelectedItem().toString())) / 100)
                + ((Integer.parseInt(tabelData.getValueAt(i, 4).toString()) * Integer.parseInt(persenUAS.getSelectedItem().toString())) / 100);
        return nilai;
    }

    public Integer[] dataNilaiUas() {
        int a = 0;
        int b = 0;
        int c = 0;
        int d = 0;
        int e = 0;
        int f = 0;

        for (int i = 0; i < tabelData.getRowCount(); i++) {
            int pilah = Integer.parseInt(tabelData.getValueAt(i, 4).toString());
            if (pilah < 50) {
                a = a++;
            } else if (pilah >= 50 && pilah <= 60) {
                b = b++;
            } else if (pilah > 60 && pilah <= 70) {
                c = c++;
            } else if (pilah > 70 && pilah <= 80) {
                d = d++;
            } else if (pilah > 80 && pilah <= 90) {
                e = e++;
            } else {
                f = f++;
            }
        }

        Integer[] dataNilai = {a, b, c, d, e, f};
        return dataNilai;
    }

    public Integer[] dataNilaiAkhir() {
        int a = 0;
        int b = 0;
        int c = 0;
        int d = 0;
        int e = 0;
        int t = 0;

        for (int i = 0; i < tabelData.getRowCount(); i++) {
            String pilah = tabelData.getValueAt(i, 5).toString();
            if ("A".equalsIgnoreCase(pilah)) {
                a++;
            } else if ("B".equalsIgnoreCase(pilah)) {
                b++;
            } else if ("C".equalsIgnoreCase(pilah)) {
                c++;
            } else if ("D".equalsIgnoreCase(pilah)) {
                d++;
            } else if ("E".equalsIgnoreCase(pilah)) {
                e++;
            } else {
                t++;
            }
        }

        Integer[] dataNilai = {a, b, c, d, e, t};
        return dataNilai;
    }
}
