/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uas.app;

import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.SwingWrapper;
import org.knowm.xchart.demo.charts.ExampleChart;

/**
 *
 * @author user
 */
public class StatistikForm extends javax.swing.JFrame {

    /**
     * Creates new form StatistikForm
     */
    public StatistikForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        uasChart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        naChart = new javax.swing.JPanel();
        dataUts = new javax.swing.JPanel();
        maxUts = new javax.swing.JLabel();
        maxUtsData = new javax.swing.JLabel();
        minUts = new javax.swing.JLabel();
        minUtsData = new javax.swing.JLabel();
        aveUts = new javax.swing.JLabel();
        aveUtsData = new javax.swing.JLabel();
        dataUas = new javax.swing.JPanel();
        maxUas = new javax.swing.JLabel();
        maxUasData = new javax.swing.JLabel();
        minUas = new javax.swing.JLabel();
        minUasData = new javax.swing.JLabel();
        aveUas = new javax.swing.JLabel();
        aveUasData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Statistik Nilai");
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 16, 0};
        layout.rowHeights = new int[] {0, 14, 0};
        getContentPane().setLayout(layout);

        uasChart.setBackground(new java.awt.Color(204, 204, 204));
        uasChart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uasChart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uasChartFocusGained(evt);
            }
        });
        uasChart.setLayout(new java.awt.GridLayout());

        jLabel1.setText("jLabel1");
        uasChart.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(uasChart, gridBagConstraints);

        naChart.setBackground(new java.awt.Color(204, 204, 204));
        naChart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout naChartLayout = new javax.swing.GroupLayout(naChart);
        naChart.setLayout(naChartLayout);
        naChartLayout.setHorizontalGroup(
            naChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        naChartLayout.setVerticalGroup(
            naChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(naChart, gridBagConstraints);

        dataUts.setBackground(new java.awt.Color(153, 153, 153));
        dataUts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dataUts.setPreferredSize(new java.awt.Dimension(150, 100));

        maxUts.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        maxUts.setText("Nilai UTS TerBesar");

        maxUtsData.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        maxUtsData.setText("0");

        minUts.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        minUts.setText("Nilai UTS Terendah");

        minUtsData.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        minUtsData.setText("0");

        aveUts.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        aveUts.setText("Nilai Rata-rata UTS");

        aveUtsData.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        aveUtsData.setText("0");

        javax.swing.GroupLayout dataUtsLayout = new javax.swing.GroupLayout(dataUts);
        dataUts.setLayout(dataUtsLayout);
        dataUtsLayout.setHorizontalGroup(
            dataUtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataUtsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataUtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aveUts)
                    .addComponent(maxUts)
                    .addComponent(minUts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(dataUtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxUtsData)
                    .addComponent(minUtsData)
                    .addComponent(aveUtsData))
                .addContainerGap())
        );
        dataUtsLayout.setVerticalGroup(
            dataUtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataUtsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataUtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxUts)
                    .addComponent(maxUtsData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataUtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minUts)
                    .addComponent(minUtsData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataUtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aveUts)
                    .addComponent(aveUtsData))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(dataUts, gridBagConstraints);

        dataUas.setBackground(new java.awt.Color(153, 153, 153));
        dataUas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dataUas.setPreferredSize(new java.awt.Dimension(150, 100));

        maxUas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        maxUas.setText("Nilai UAS  Terbesar");

        maxUasData.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        maxUasData.setText("0");

        minUas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        minUas.setText("Nilai UAS Terendah");

        minUasData.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        minUasData.setText("0");

        aveUas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        aveUas.setText("Nilai Rata-rata UAS");

        aveUasData.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        aveUasData.setText("0");

        javax.swing.GroupLayout dataUasLayout = new javax.swing.GroupLayout(dataUas);
        dataUas.setLayout(dataUasLayout);
        dataUasLayout.setHorizontalGroup(
            dataUasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataUasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataUasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataUasLayout.createSequentialGroup()
                        .addComponent(maxUas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maxUasData))
                    .addGroup(dataUasLayout.createSequentialGroup()
                        .addComponent(minUas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minUasData))
                    .addGroup(dataUasLayout.createSequentialGroup()
                        .addComponent(aveUas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aveUasData)))
                .addContainerGap())
        );
        dataUasLayout.setVerticalGroup(
            dataUasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataUasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataUasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxUas)
                    .addComponent(maxUasData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataUasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minUas)
                    .addComponent(minUasData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataUasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aveUas)
                    .addComponent(aveUasData))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(dataUas, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uasChartFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uasChartFocusGained
        // TODO add your handling code here:
        cChart = new ChartUas();
        
    }//GEN-LAST:event_uasChartFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatistikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatistikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatistikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatistikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatistikForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aveUas;
    private javax.swing.JLabel aveUasData;
    private javax.swing.JLabel aveUts;
    private javax.swing.JLabel aveUtsData;
    private javax.swing.JPanel dataUas;
    private javax.swing.JPanel dataUts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel maxUas;
    private javax.swing.JLabel maxUasData;
    private javax.swing.JLabel maxUts;
    private javax.swing.JLabel maxUtsData;
    private javax.swing.JLabel minUas;
    private javax.swing.JLabel minUasData;
    private javax.swing.JLabel minUts;
    private javax.swing.JLabel minUtsData;
    private javax.swing.JPanel naChart;
    private javax.swing.JPanel uasChart;
    // End of variables declaration//GEN-END:variables
    
    private ChartUas cChart;
}
